import "./globals.css"

import { Footer } from "@/app/_components/footer"
import { Header } from "@/app/_components/header"
import { RootProvider } from "@/app/_components/root-provider"
import { Config } from "@/config"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Noto_Sans_JP } from "next/font/google"

const notoSansJp = Noto_Sans_JP({
  weight: ["500", "700"],
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
  preload: false,
})

type Props = {
  children: React.ReactNode
}

const RootLayout = (props: Props) => {
  return (
    <html lang={"ja"} suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen font-sans antialiased w-full",
          notoSansJp.variable,
        )}
      >
        <RootProvider>
          <Header />
          {props.children}
          <Footer />
        </RootProvider>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  metadataBase: new URL(process.env.URL ?? "http://localhost:3000"),
  title: Config.blogTitle,
  description: "Generated by create next app",
  robots: { index: false },
  openGraph: { images: [Config.homeOgImageURL] },
}

export default RootLayout
